name: Build flask app

on: [push]
jobs:
  Build-Flask:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Start."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build a container image
        run: |
          docker build -t flask-test:latest .
      - name: Run a container
        run: |
          docker run -p 5000:5000 flask-test &
          sleep 3
          curl `hostname -I`:5000
          kill -9 `ps -ef | grep flask | awk '{print $1}'`
